pluginManagement {
    repositories {
      /*  maven {
            url = uri("https://maven.myket.ir")
        }*/
        maven {
            url = uri("https://maven.tapsell.ir")
        }
        maven { setUrl("https://jitpack.io") }
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
       /* maven {
            url = uri("https://maven.myket.ir")
        }*/
      /*  maven {
            url = uri("https://maven.tapsell.ir")
        }*/
        maven { setUrl("https://jitpack.io") }
        google()
        mavenCentral()

    }
}

rootProject.name = "libraryAd"
include ':app'
include ':provider-tapsell'
include ':provider-admob'
include ':provider-yandex'
include ':core'
